#!/usr/bin/with-contenv bash
# Wazuh App Copyright (C) 2020 Wazuh Inc. (License GPLv2)

set -e

if [ "$KAFKA_BROKER_LIST" != "" ]; then
  >&2 echo "Customize Kafka Broker list"
sed -i "s/INSERT_BROKER_LIST/$KAFKA_BROKER_LIST/g" /etc/filebeat/filebeat.yml
fi

if [ "$KAFKA_TOPIC" != "" ]; then
  >&2 echo "Customize Kafka topic"
sed -i "s/INSERT_TOPIC/$KAFKA_TOPIC/g" /etc/filebeat/filebeat.yml
fi


chmod go-w /etc/filebeat/filebeat.yml || true
chown root: /etc/filebeat/filebeat.yml || true
