group name=plesk,
   rule id=100100 level=0
      decoded_aspleskExtensionUpgradeddecoded_as
      descriptionGrouping of plesk rulesdescription
   rule
   rule id=100101 level=3
      if_sid100100if_sid
      regex^.+s'Extension upgraded'regex
      descriptionPlesk extension upgraded.description
   rule

   rule id=100102 level=0
      decoded_aspleskComponentUpdateddecoded_as
      descriptionGrouping of plesk rulesdescription
   rule
     rule id=100103 level=3
      if_sid100102if_sid
      regex^.+s'Plesk component updated'regex
      descriptionPlesk component upgraded.description
   rule

     rule id=100104 level=0
      decoded_aspleskUserLoggedIndecoded_as
      descriptionGrouping of plesk rulesdescription
   rule
     rule id=100105 level=3
      if_sid100104if_sid
      regex^.+s'Plesk user logged in'regex
      descriptionPlesk user logged in.description
   rule
group

group name=fail2ban,
   rule id=100010 level=0
      decoded_asfail2bandecoded_as
      descriptionGroup of Fail2ban rulesdescription
   rule
   rule id=100011 level=3
      if_sid100010if_sid
      regexNOTICEs+[S+]sBanregex
      descriptionIP Banned by Fail2bandescription
   rule
   rule id=100012 level=3
      if_sid100010if_sid
      regexNOTICEs+[S+]sUnbanregex
      descriptionIP Unbanned by Fail2bandescription
   rule
   rule id=100013 level=3
      if_sid100010if_sid
      regexFoundregex
      descriptionIP Found by Fail2bandescription
   rule
group